### ISSUE TITLE
Funcion pointer not instantialized

### ISSUE THREAD

**Issue by Guoanshisb** [smackers/smack#139]
https://github.com/smackers/sv-benchmarks/blob/master/c/heap-manipulation/dll_of_dll_true-unreach-call.i#L663

In the bpl file generated, it is translated to `$p1 := $bitcast.ref.ref(insert_fnc);`, which caused a false bug.

**Comment by michael-emmi** [comment]
This is happening due to our current policy of selecting possible call targets, which is restricted to functions (a) whose address is taken at some point, and also (b) have the same type as the called function. In this program the type `void (*insert_fnc)()` does not match `void dll_insert_master(struct master_item **dll)`, so `dll_insert_master` is not considered as a possible target — though it should be. Here is the offending code:

https://github.com/smackers/smack/blob/develop/lib/smack/SmackInstGenerator.cpp#L568

Perhaps we should relax our rule on type compatibility in order to achieve better soundness. On the other hand, this might also open the door to lots of false possible matches in other cases.

Other approach would be to leverage DSA here to determine a list of possible call-target aliases.

Any bright ideas?

**Comment by zvonimir** [comment]
I already tried to leverage DSA to address this issue, and in particular I tried using its `CallTargetFinder` pass. My implementation still did not manage to find the correct target for the call such as the above one (I created a smaller example illustrating this problem). In the limited amount of time I dedicated to this, I did not manage to figure how how come DSA could not find this target function. So I stashed my changes and moved on.

I do not have any amazing ideas (besides my failed DSA attempt) on how to address this issue.

**Comment by michael-emmi** [comment]
Well simply dropping the type-compatibility check would work — the only question is whether we are willing to deal with the possible repercussions on other examples.

**Comment by zvonimir** [comment]
This is not fixed after all. My fix introduced issues downstream since SMACK would invoke procedures that ended up not being defined in the generated Boogie file. The reason for this is interplay between function pointers and vararg procedures. This requires some more thought.
