### ISSUE TITLE
Imprecise memory region separation 

### ISSUE THREAD

**Issue by Guoanshisb** [smackers/smack#140]
https://github.com/smackers/sv-benchmarks/blob/master/c/ldv-regression/alias_of_return.c_true-unreach-call.i#L25

`a` is stored in `$M.0`

https://github.com/smackers/sv-benchmarks/blob/master/c/ldv-regression/alias_of_return.c_true-unreach-call.i#L32

`*q` is stored in `$M.1` so `a` does not get modified.

**Comment by michael-emmi** [comment]
Interesting indeed. This seems to be a problem with DSA’s bottom-up phase, since `return_self`’s graph merged into `main`’s should end up merging `main`’s nodes — see attached graphs.

[bu.main.pdf](https://github.com/smackers/smack/files/21044/bu.main.pdf)
[local.main.pdf](https://github.com/smackers/smack/files/21043/local.main.pdf)
[local.return_self.pdf](https://github.com/smackers/smack/files/21042/local.return_self.pdf)

**Comment by michael-emmi** [comment]
I have determined that the merge of `return_self`’s graph into `main`’s is not happening because `return_self` does not appear in the auxiliary call site list in `main`’s graph during the BU phase. According to the source, non-local DSA phases should use this auxiliary call site list in place of the function’s actual call site list.

Apparently, the auxiliary call site list is only populated with the list of actual call sites (per function) in a DSA phase which is initialized with the `resetAuxCalls` parameter. Currently, the only DSA phase which sets this parameter is the `CompleteBUDataStructures` phase, which we do not use. It seems to me that we should be resetting/initializing the auxiliary call site list *at some point* — otherwise the BU phase would not inline callee graphs, since it sees no call sites.

This raises the following questions:

1. Should the `BUDataStructures` phase reset the auxiliary call site list?

2. Should we be using `CompleteBUDataStructures` phase instead of `BUDataStructures`?

3. Is the `CompleteBUDataStructures` deprecated?

Perhaps we should contact somebody who knows more about these passes.

**Comment by michael-emmi** [comment]
Another possibility: perhaps the auxiliary list is supposed to be initialized in the local phase? The following line would suggest that.

    https://github.com/smackers/smack/blob/develop/lib/DSA/Local.cpp#L1553

However, this initialization may come too early since the call graph is computed afterwards.

**Comment by michael-emmi** [comment]
In fact the last possibility seems like the best: the auxiliary call site list should probably be initialized in the local phase, after the actual call sites are populated by the `GraphBuilder`.

https://github.com/smackers/smack/blob/develop/lib/DSA/Local.cpp#L1555

Reordering those statements indeed fixes this issue, hopefully it does not create other problems.
