### ISSUE TITLE
Devirtualization constructing incomplete bounce function.

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#146]
The assertion in the example should fail, and yet SMACK does not catch that func2 can be invoked.

````C
#include "smack.h"

void (*fptrs[2])();

void func2() {
  assert(0 != 0);
}

void add_func(void (*f)()) {
  fptrs[1] = f;
}

void func1() {
  add_func(func2);
}

int main(void) {
  fptrs[0] = func1;
  fptrs[0]();
  fptrs[1]();
  return 0;
}
````

**Comment by zvonimir** [comment]
As it turns out, commenting out this line fixes this problem:
https://github.com/smackers/smack/blob/develop/lib/DSA/EquivClassGraphs.cpp#L86
I've been debugging this, and the `EquivBUDataStructures` pass generates what I would consider to be a correct call graph for the above example. The `CompleteBUDataStructures` pass generates a call graph that is missing the fact that `main` invokes `func2` as well.
Now, it could be that this is only masking the actual source of this bug, but I am not sure how to properly verify this.
