### ISSUE TITLE
Add mode for svcomp language extensions without heuristics

### ISSUE THREAD

**Issue by IanBriggs** [smackers/smack#159]
To troubleshoot complicated benchmarks it would be nice to turn heuristics off and control all the parameters. This would allow debugging of the heuristics. 

We should be able to use the svcomp extensions and have smack work the same otherwise.

**Comment by IanBriggs** [comment]
After looking through the code, it seems like this can be achieved by using `-x svcomp --verifier=corral`.  This prevents `verify_bpl_svcomp` from being called, which is where all of the heuristics are set.

**Comment by IanBriggs** [comment]
Actually, on _further_ inspection of the code, if `-x svcomp --verifier=corral --svcomp-property all.prp` is used, then the property file is never accessed or used (since this is done in `verify_bpl_svcomp`, which is avoided by using `--verifier=corral`).

This logic is debatable...  If we know that SMACK can't check for a certain property before getting to the bpl verification phase, why should we bother with the bpl verification phase at all?

Can anyone think of a reason to continue processing the input if the property specified by `--svcomp-property` is not supported?

**Comment by zvonimir** [comment]
We basically do not use the property file to establish which properties should be checked. At this point, we use it in a hacky way just so that we can opt out from certain categories that we are not competing in and that can be recognized by looking at the property file, such as MemorySafety. Property file is not used at all to establish which property is being checked - we assume that we are always checking reachability of `__VERIFIER_error` since we do not compete in categories other than those that enforce this property to be checked.
Does that make sense?

**Comment by shaobo-he** [comment]
Close this issue as this is mentioned in a more recent issue #324
