### ISSUE TITLE
LLVM intrinsics being removed

### ISSUE THREAD

**Issue by keram88** [smackers/smack#162]
An llvm instruction such as
%2 = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 %0, i32 %1)
is being dropped in the process of converting the IR code to Boogie.

This appears to be connected to one or several optimization passes.

**Comment by Guoanshisb** [comment]
I would like to also use this issue for implementing support for this intrinsic. Please treat it as a reminder.

**Comment by michael-emmi** [comment]
This instruction is being removed by the passes run prior to Boogie code generation. Disabling the `StructReturnToPointer` pass preserves this instruction. However, as far as I am aware, we require this pass for other reasons.

There are two ways forward here:

1. Revisit our original design, and see whether we shouldn’t handle the translation of structures (returned from functions) directly, rather than trying to discard them before translation.

2. Figure out why this particular call is being dropped. Hint: I suspect it has something to do with the function being an intrinsic, and its definition not appearing in the module.

**Comment by Guoanshisb** [comment]
@michael-emmi 
I agree with your proposals. Let's discuss them in detail.

> Revisit our original design, and see whether we shouldn’t handle the translation of structures (returned from functions) directly, rather than trying to discard them before translation.

I was wondering what alternative that we have other than using `StructReturnToPointer` pass. No 
clean solution came to mind so far.

> Figure out why this particular call is being dropped. Hint: I suspect it has something to do with the function being an intrinsic, and its definition not appearing in the module.

Yes. Another observation is that if we keep `StructReturnToPointer` pass and remove dead code elimination pass, then this call is preserved. So I was wondering if dead code elimination instead of `StructReturnToPointer` pass drops it.

**Comment by zvonimir** [comment]
I think that the dead code elimination pass does the right thing. It is likely that the `StructReturnToPointer` pass for some reason creates dead instructions. So we should first probably focus on figuring out how `StructReturnToPointer` pass works.

**Comment by zvonimir** [comment]
Ok, I a having trouble debugging this without having a small bc file showing this issue. Could someone attach such a file to this thread? The smaller it is the better.

**Comment by MichaelFQuigley** [comment]
Here is a rust file that does the same thing with llvm.sadd.with.overflow.
[test.txt](https://github.com/smackers/smack/files/201722/test.txt)
Here is the accompanying bc file:
[out_bc.txt](https://github.com/smackers/smack/files/201729/out_bc.txt)

**Comment by Guoanshisb** [comment]
Hey guys,

I did some experiments this afternoon.

First, I renamed `llvm.smul.with.overflow.i32` to `foo` and it also got dropped.
Second, I instrumented `foo` with a body and run SMACK on the modified `bc` file. `foo` was not dropped.
Finally, I copied `foo` function that I wrote to a file, renamed to `llvm.smul.with.overflow.i32` and tried to link it with the original `bc` file. llvm-link gave an error.

I still didn't figure out what happened. But I hope it would help you guys to debug.

Shaobo

**Comment by michael-emmi** [comment]
The cause is that this intrinsic function is given the `readnone` attribute — meaning that it does not read nor write to memory — and that `StructReturnToPointer` transforms the call so that its return value is ignored. The result is a function that doesn’t touch memory and whose return value is ignored, which is rightly pruned by dead-code elimination.

Perhaps the right fix is to have `StructReturnToPointer` update its transformed functions’ attributes to remove any `readnone`s and `readonly`s. The only thing to make sure is that the `readnone` attribute doesn’t get re-added before dead-code elimination.

I’ll try out this fix.

**Comment by michael-emmi** [comment]
For the moment I did not implement the previous idea, since LLVM seems to (re-)add the `readnone` attribute liberally to these intrinsic functions, e.g., during parsing, which could make implementing that idea a bit fragile.

Instead I simply disabled the struct-return elimination code on functions without definition, and this prevents it from being applied to intrinsics.

**Comment by Guoanshisb** [comment]
@michael-emmi Thanks for the fix. Now we need to think about how to implement this intrinsic. What ideas do you have in mind?

**Comment by zvonimir** [comment]
@Guoanshisb : I think you should open a new issue to discuss how to implement the translation.
