### ISSUE TITLE
SMACK crashes when program contains function with "expr" in the name

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#173]
Consider the following program,

``` C
#include "smack.h"

void expr()
{
  int expr = 0;
  assert(expr);
}

int main()
{
  expr();
  return 0;
}
```

SMACK crashes on it. I think it is related to the following lines,
https://github.com/smackers/smack/blob/develop/lib/smack/SmackModuleGenerator.cpp#L81-L84

**Comment by michael-emmi** [comment]
Can you list a failing example?

**Comment by keram88** [comment]
The following function declaration causes the error:
@"_ZN34_$LT$expr..smack..Vec$LT$T$GT$$GT$3pop17hbdf51b1237713431E"

The link to the IR file is:
<script src="https://gist.github.com/keram88/beb8552047ad4beb0d756d4dc84c7eee.js"></script>

LLVM appears to be quite flexible in what it will accept as a valid identifier:
https://llvm.org/docs/LangRef.html#identifiers
Specifically, quotes and escape sequences can be used to write otherwise illegal characters in the identifier.
