### ISSUE TITLE
Avoid havoc command for the encoding of select instruction

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#174]
The alias analysis for Boogie programs used by angelic verification does not support **havoc** command which is part of the current encoding of select instruction. Recall the current encoding **havoc**s the return value and assumes the return value equal to two possible operands depending on the condition (https://github.com/smackers/smack/blob/develop/lib/smack/SmackInstGenerator.cpp#L422-L435).

I was wondering if the **havoc** command is needed here since LLVM uses SSA form, which means the return variable is not assigned before the select instruction. Another solution is to assign `if else` expression to the return variable.

**Comment by michael-emmi** [comment]
SSA means single *static* assignment; that variable can be assigned multiple times in a loop.

Translating
````
z = select w, x, y
````
to
````
z := if w == 1 then x else y;
````
as you suggest sounds like a better idea for now.

But this begs a more serious question: why doesn’t that verification tool budge on this one? Last I knew `havoc` was a valid Boogie statement. Should we not be writing Boogie programs with the `havoc` statement? Since when was `havoc` blacklisted? Is Smack forever prohibited from emitting the `havoc` statement?

Any insight/elaboration on that would be useful. What does MSR say?

**Comment by akashlal** [comment]
Testing

**Comment by michael-emmi** [comment]
@akashlal Agreed, and I prefer Shaobo's translation anyways. Just making sure we still have the right to use `havoc` if needed 🙂

**Comment by michael-emmi** [comment]
@Guoanshisb did you want me to implement this, or will you?

**Comment by Guoanshisb** [comment]
@michael-emmi Let me try to implement it in `av-support` branch first. Then you can review my implementation after a pull request is submitted.

**Comment by zvonimir** [comment]
@shaobo-he : has this been done?

**Comment by shaobo-he** [comment]
The new encoding is implemented in `av-support` branch.

**Comment by zvonimir** [comment]
Could we cherry-pick the needed commits or something like that, so that we can address this issue sooner rather than later? Or are you planning to merge av-support sometime soon?

**Comment by shaobo-he** [comment]
I created a new pull request (#277) to address the issue. Please take a look at it.
