### ISSUE TITLE
Incorrect encoding for negative operands of unsigned integer comparison instructions

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#187]
Consider the following program,

```C
#include "smack.h"

int main()
{
  unsigned x = 10;
  __VERIFIER_assert(x < ((unsigned)-2));
}
```

The assertion should not fail while SMACK reports a bug. It seems that SMACK treat the negative operand of `ult` instruction as it is. So instruction `%1 = icmp ult i32 10, -2, !dbg !853` is translated to `$i0 := $ult.i32(10, $sub.i32(0, 2));`, which results in the assertion failure.

**Comment by zvonimir** [comment]
Maybe an even bigger problem (but same root cause) is the fact that `UINT_MAX` gets translated as -1.

**Comment by michael-emmi** [comment]
This is a limitation of encoding C integer types with Boogie int types. Notice that things work as you’d expect when bit-precision is enabled.

A general fix which maintains our current integer encoding can be seen in the `integer-encoding-fix` which wraps integers used as unsigned types in the `$tou` function:
````
function $tou.i32(i: int) returns (int) {
  if i >= 0 && i < 4294967296 then i else $mod(i,4294967296)
}
````
You can verify that the fix works by wrapping the `$sub.i32(0, 2)` value:
````
$i0 := $ult.i32(10, $tou.i32( $sub.i32(0, 2) ));
````
The problem with this fix is that it is generally very expensive since modulo operations are sprinkled all over the place.

A less general fix that would work for this example would be to translate integer literals according to their context. For example, in this case we could see that the literal `-2` is used as an unsigned argument, and thus translate it to `UINT_MAX - 1`. This could work for argument literals, but would require more elaborate analysis beyond that, of questionable value.

**Comment by michael-emmi** [comment]
Another thing to consider — not a quick fix — would be to basically do what the `integer-encoding-fix` does, yet run some analysis, e.g., interval analysis, to eliminate as many `$tou` operations as possible. The worst case would still be bad, of course.

**Comment by Guoanshisb** [comment]
@michael-emmi Thanks for your input. I have a quick question, is there a problem with our current integer encoding for arithmetic? I can see that unsigned overflow is one.

**Comment by michael-emmi** [comment]
@Guoanshisb not sure I understand your question, because your example demonstrates that there is a problem with our integer encoding: we do not give the correct unsigned interpretation to integer types.

Our bit-precise mode works because the bit representation of an integer can be read directly as a signed or unsigned number — no conversion necessary. For example, the byte representation `11111110` of `-2` is read directly as `254` unsigned or `-2` signed. This is not true for our Boogie-integer encoding. While positive non-overflowing integers can be read directly as signed or unsigned, negative integers and overflowing integers must undergo some conversion, e.g., to be read as unsigned. You need an operation that converts `-2` to `254`.

A general fix to our integer encoding would need something like the `$tou` function I mentioned above such that `$tou.i8(-2) == 254`.

**Comment by shaobo-he** [comment]
This issue has been (partially) resolved because for negative constants occurring in the unsigned comparison operations, we convert them into their 2's complement values.

**Comment by zvonimir** [comment]
Do we have a regression for this?

**Comment by shaobo-he** [comment]
No, I can add one if it's needed.

**Comment by zvonimir** [comment]
Please add one and reference this issue in your commit. Thanks!
