### ISSUE TITLE
Generating address axioms for removed globals

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#191]
I just noticed this piece of code in a Boogie file generated by SMACK:
```
const .str: ref;
axiom (.str == $sub.ref(0, 16));
const {:count 16} .str.1: ref;
axiom (.str.1 == $sub.ref(0, 32));
const {:count 14} .str.2: ref;
axiom (.str.2 == $sub.ref(0, 46));
const {:count 31} .str.3: ref;
axiom (.str.3 == $sub.ref(0, 77));
const {:count 14} .str.4: ref;
axiom (.str.4 == $sub.ref(0, 91));
```
These globals are not mentioned anywhere else in the file. I believe this indicates that we are generating these axioms even for globals that are not used anywhere. It might be a simple optimization to clean this up.

**Comment by michael-emmi** [comment]
At the moment it is not clear what filter can be used to rule out the `const` declarations here. We filter out their static initializers when the address is either read or not unnamed. The following regression prevents us from using that same filter to remove these declarations, since there are strings (they have unnamed addresses) which are never read but nevertheless used:

https://github.com/smackers/smack/blob/develop/test/basic/func_ptr_vararg.c
