### ISSUE TITLE
Using SMACK for Fortran code

### ISSUE THREAD

**Issue by gunjanaggarwal** [smackers/smack#213]
Hi,

I would like to know if it is possible to use SMACK for Fortran code. Having found that it is possible to provide LLVM IR to SMACK as input and that there is a Tool (DragonEgg: https://dragonegg.llvm.org/#gettingrelease) which can generate LLVM IR from Fortran gives me a hope that we can analyze Fortran code using SMACK. But the problem is that DragonEgg is not supported for newer versions of LLVM and the latest LLVM version supported is 3.3.

Do you think it is possible to use LLVM IR generated via DragonEgg  as an input to SMACK?

Thanks,
Gunjan

**Comment by zvonimir** [comment]
This is a great question, and we have been thinking about this direction ourselves. As you noted, DragonEgg is not supported any more, and you will not be able to run SMACK on DragonEgg-generated LLVM IR files without putting a good amount of effort to "downgrade" SMACK back to LLVM 3.3. We decided that is not something we want to pursue at this point since "downgrading" is not really that appealing :).

However, there is some good news here. Several years ago, Flang effort was started on building a Fortran front-end for LLVM from scratch: https://github.com/llvm-flang/flang
This effort was picked up by PGI (http://www.pgroup.com/) and the rumor they started at the Supercomputing conference last year was that they will have a Flang release ready sometime in the spring/summer of 2017. Once that happens, we will have the whole Fortran toolflow ready for SMACK, at which point we would love to try out SMACK on Fortran programs. It would be great if this would be something you would be interested to contribute to.

**Comment by zvonimir** [comment]
Dear @gunjanaggarwal, I just want to inform you that the most recent release of SMACK includes support for verification of FORTRAN programs, in case that is something you are still interested in. We would love to get some feedback from you.
