### ISSUE TITLE
Generate smack.c via a Python script

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#308]
Currently smack.c is hand-crafted and uses macros to capture patterns in function declarations. Therefore, smack.c is not well organized. Using a Python script to automatically generate smack.c is a promising solution to this problem.

**Comment by zvonimir** [comment]
This is related to the discussion started in this pull request: https://github.com/smackers/smack/pull/307
I thought more about this and I do think it is probably a good idea. However, how would this work with large projects where we manually include `smack.h` and manually link with `smack.c`?
Instead of generating these files dynamically every time SMACK is run, how about we think of it as a parser generator, and actually have a python script that generates these files, which we then commit into the repo. I hope this makes sense.

**Comment by michael-emmi** [comment]
What is the workflow you have in mind with this “manual linking” of `smack.c`? Do you mean that the user invokes `llvm2bpl` directly, rather than invoking the Python `smack` script?

In the latter case, the user presumably provides LLVM bitcode to `smack`, in which case we can generate and link the corresponding `smack.c` module, just before running `llvm2bpl`.

The potential problems I see with the user maintaining a `smack.c` module are that (a) their module may be inconsistent with future updates to Smack, since the `smack.c` we generate can change across versions, and (b) since the generated `smack.c` module depends on options to `smack` — currently memory safety and choice of memory model, but future versions could add additional dependencies — fixing `smack.c` would limit the user to verification queries with the same options, e.g., cannot do both with and without memory safety with the same `smack.c`.

My intuition on best practices for software maintenance suggests that we should try to avoid encouraging users to store a generated `smack.c` module.

**Comment by zvonimir** [comment]
Coming back to this. Why would we generate `smack.c` automatically, instead of generating Boogie code directly (via a python script invoked from top.py)?

**Comment by michael-emmi** [comment]
Good point!

I’d say generating Boogie code directly should be preferred, so long as none of those Boogie-code declarations actually depend on the compiler or preprocessor. I assumed we are talking about the declarations inside `__SMACK_decls`, and it seems that they are independent.

Would there be any reason that the other `__SMACK_` and `__VERIFIER_` function definitions could not be generated in the same way?

It seems that the only remaining function definitions in `smack.c` are `exit` and `calloc`, and they probably don’t belong there in any case. Their definitions are both given in C code, and according to our current conventions, those should go into a `stdlib.c` file.

**Comment by michael-emmi** [comment]
As far as I remember, we had put in `SmackRep.cpp` whatever we could not figure out how to put in `smack.c`; ideally, we’d have wanted everything in `smack.c`. For instance, C’s macro system allowed us to express loops and such to allow programmatic code generation. But there were some quantities, e.g., target-architecture specific quantities like pointer size, e.g., input-program specific quantities like the number of global variables, that we only had available within LLVM passes.

I think it would be worth reconsidering the interface between the prelude and the generated program module, like you suggest.

**Comment by zvonimir** [comment]
@liammachado : could you look into moving the prelude generation you implemented from Python into C++ code instead?
See our discussion above. We kind of observed that many axioms and functions sometimes slow down verification, and at the C++ level it should be easier to for example generate axioms only for bit-widths that are actually being used in the program.

**Comment by liammachado** [comment]
Yep, I'll look into that.

**Comment by zvonimir** [comment]
Closed by eafc754
