### ISSUE TITLE
Can SMACK convert recursive and asynchronous C programs to Boogie

### ISSUE THREAD

**Issue by ezudheen** [smackers/smack#318]
Hi,

I would like to know whether SMACK can convert recursive and asynchronous C programs to Boogie program

Thanks
Ezudheen

**Comment by ezudheen** [comment]
--------------------
if (*) {
  x++;
} else {
  y++;
}
------------------
havoc random_value

if (random_value) {
  x++;
} else {
  y++;
}
-----------------------------------------
Asynchronous programs take non-deterministic execution paths. This will used for encoding concurrent programs (say either thread-1 or thread-2 will execute first)

**Comment by ezudheen** [comment]
Hi,

1. Can smack convert SVCOMP recursive benchmark programs to Boogie Program,
One sample conversion is given below.

2. Can smack handle non-deterministic transitions in recursive programs as
given below

main() {

foo(5);

}

foo(int n) {

  int m = __VERIFIER_nondet_int();

  if (m) {

    foo(n-1);

  } else {

    foo(n-2);

   }
}


Thanks
Ezudheen
PhD student, Indian Institute of Science Bangalore, India

**Comment by ezudheen** [comment]
Thanks very much

Ezudheen

**Comment by computereasy** [comment]
@zvonimir Hello, one quick question. 

I am using `Smack` to check my program with recursive calls. I first tried to use the default `Corral` backend verifier, and it becomes quite slow for about 800 LOC LLVM IR code, sometimes timeout.

But after changing to `Boogie`, it turns out to be rapid. Roughly 10 seconds to finish. 

I wonder if that's because `Corral` does not properly unroll recursive call. Am I missed anything here? Thanks.

**Comment by zvonimir** [comment]
@computereasy : Sorry, but could you please create a separate issue for this, and we'll try to assist you with your performance-related question? Thanks!

**Comment by computereasy** [comment]
@zvonimir no problem. I think I have learned from other threads that the `allVars` option of `Corral` can largely speed up the reasoning. I don't have this issue for now.
