### ISSUE TITLE
Adding support for bitvectors

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#33]
Precisely supporting bitvector operations is important for some examples. Boogie supports bitvectors, and so we should add support for bitvectors to SMACK as well. The biggest issues is how to define our memory model in that case.

Let's discuss this first before we act on it...

**Comment by zvonimir** [comment]
I guess we should close this one now that bit-vectors are implemented.

**Comment by Guoanshisb** [comment]
Hi guys,

There is obviously a scalability issue of SMACK  when it is applied on **DeviceDriver64** category of SVCOMP benchmarks that requires reasoning about bit-vectors. I think it would be good to improve our support for bit-vectors in order to fix this issue.

I manually inspected some benchmarks[[1]](https://github.com/sosy-lab/sv-benchmarks/blob/master/c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--scsi--advansys.ko-entry_point_true-unreach-call.cil.out.c) and it seems that the number of variables requiring bit-vectors is limited (mainly flags[[2]](https://github.com/sosy-lab/sv-benchmarks/blob/master/c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--scsi--advansys.ko-entry_point_true-unreach-call.cil.out.c#L15268)). So I think maybe a dependence analysis could allow us to use bit-vector on these variables while model others as integers though interprocedural support and pointer aliasing could be a big problem. Moreover, Akash's paper, [Powering the Static Driver Verifier using Corral](http://research.microsoft.com/pubs/219595/SdvCorralFSE.pdf) also provides a very reasonable solution. I remember you have tried it while it might not work well.

Please let me know your thoughts.

Thanks,
Shaobo

**Comment by michael-emmi** [comment]
This issue (support for bit-vectors) is certainly closed since SMACK supports bit-vectors now.

Improving the scalability of bit-vector support is a separate issue: #149.
