### ISSUE TITLE
Handling llvm.lifetime intrinsic

### ISSUE THREAD

**Issue by bjohannesmeyer** [smackers/smack#386]
I'm trying to run ctverif on an .ll file and it gives me the following error when running SMACK in debug mode:

```
[dsa:local] Unhandled intrinsic: llvm.lifetime.start.p0i8
Unhandled intrinsic
UNREACHABLE executed at /root/smack/lib/DSA/Local.cpp:1185!
```

As far as I understand, `llvm.lifetime.start` and `llvm.lifetime.end` are basically no-ops, so is there any way I can tell SMACK to ignore them?

**Comment by zvonimir** [comment]
Hmmm, this is strange since this `case` branch should catch them: https://github.com/smackers/smack/blob/develop/lib/DSA/Local.cpp#L1166
I don't really know how come that doesn't happen.
Is `llvm.lifetime.start.p0i8` some special intrinsic that is not the same as `llvm.lifetime.start` and they don't have the same ID? I am not sure and I would have to debug more. Can you maybe attach the ll file?
We would also certainly appreciate if you could give fixing this a try!

**Comment by shaobo-he** [comment]
Closed this issue because we didn't get any responses. @bjohannesmeyer feel free to reopen it if you can produce a .ll or .bc file.
