### ISSUE TITLE
Smack time out

### ISSUE THREAD

**Issue by ireneGP** [smackers/smack#405]
Hello Smackers,

I am using `smack` to model checking some LLVM IR code. On average the size of my IR code samples range from a few thousands to 100k. So right now I am using the following configurations, and get a bunch of "timeout" (roughly 130 out of 1000 samples):

    timeout 10m smack --unroll=10 XXX.ll

On one hand, I will see if there is space to optimize my LLVM IR code and reduce the size (but that may not directly lead to speedup `smack`), on the other hand, could anyone shed some lights on certain principled strategies to speedup `smack`? I tried to get rid of `unroll`, but perhaps that would lead to too many false negative, right? I also tried to reduce the unroll number, say 5, or 2. But that seems does not help too much.

**Comment by zvonimir** [comment]
If you run `smack --help`, you can see all the command line options for SMACK and their descriptions. There is an option called `--time-limit` that you can use to set the timeout on the backend verifier used by SMACK (e.g., Corral). Given that the total runtime of SMACK is almost always dominated by the runtime of the backend verifier, this basically sets the timeout of SMACK. By default it is set to 1200 seconds.

**Comment by zvonimir** [comment]
Regarding your question about time outs and scalability, well, there is potentially no straightforward answer. It could be that you are hitting the limitations of SMACK in terms of scalability, which depends on the size of the input program, its complexity, and the kinds of properties you are trying to verify.
As you already noted, you can play with the `--unroll` parameter.
You can try to use Boogie instead of Corral as the backend verifier, but doing `--verifier=boogie`, which sometimes helps.
You can try passing different options to Corral to try to speed up its heuristics, such as `--verifier-options="/trackAllVars"`, which can help for some benchmarks.
We can try to help you out more if you could describe your usage scenario, benchmarks, and properties.

**Comment by zvonimir** [comment]
Hi @ireneGP. Any luck with this benchmark?
We would like to support your effort in any way we can, so please let us know how we could maybe help out. We could even set up a (brief) telecon if that would be useful.

**Comment by ireneGP** [comment]
@zvonimir Thank you for the kind notes! I appreciate it a lot. 

I tweaked the configs according to your suggestions, and it seems that so far, the noticeable improvement comes from changing unroll from 10 to 5. 

I was traveling but will follow up since next week. Hope I can work out some well scoped samples that may get you some intuitions here, if needed. 

Thanks again. Take care.

**Comment by ireneGP** [comment]
@zvonimir  Thank you again for your kind support. I was distracted by something else but just have more time to hack. 

So overall, it seems that recursive call could dramatically slow down `Smack`, if I didn't make any mistake or bug here. I am planning to manually rewrite my recursive calls into loops. Because my recursive call is conceptually a traversal on the call **tree**, it's a bit difficult to do so, but it is solvable.

**Comment by zvonimir** [comment]
Hmmmm, coming back to this, I don't think that rewriting recursive calls as loops will help, at least when Corral is used. Since under the hood Corral actually rewrites loops into tail-recursive procedures, and so you would go back to recursion anyways. I suspect it would not help much when Boogie is used either.

In general, large loops/recursion are a problem for any bounded verifier. So you can think about how many unrollings you need as well as if you can rewrite your code to use less loops/recursion. Alternatively, SMACK has a usage mode where it does not perform bounded verification, but instead relies on manually provided loop invariants. If this becomes a major bottleneck for you, we could revisit this mode and see if you could use it in your setting.
