### ISSUE TITLE
Interpret the Boogie outputs

### ISSUE THREAD

**Issue by ireneGP** [smackers/smack#420]
Hello, 

I am using the `Boogie` backend to do some model checking tasks with recursive call, and it seems much faster than the `Corral` backend verifier. For instance, a task verified by `Boogie` takes about 10 seconds to finish, while `Corral` could probably timeout. 

But the problem is to interpret the counter example of `Boogie`. I pasted an output here:

![boggie](https://user-images.githubusercontent.com/44623557/54670404-e1f5c700-4af3-11e9-8634-b78010b26411.png)

`Corral` gives the "execution trace" of a counter example, while I basically cannot interpret anything from the above output. Could anyone shed some lights on how to interpret this results? Note that my LLVM IR is not compiled from high-level language, but rather from reverse engineering. So I don't have those debug symbol in the IR code. Am I expected to manually insert debug symbols? Thanks!

**Comment by ireneGP** [comment]
OK, I tried to manually insert the debug meta data into LLVM IR. That works.

**Comment by zvonimir** [comment]
Just to add something here. Note that Boogie does not have a great support for generating counter examples since it does not leverage automatically the debug annotations from the source code. So when using Boogie you often have to step through the actual bpl file.
Corral does a much better job in this respect and generates much more readable counter examples in terms of the original source code lines. However, as you probably already noticed, we generate debug info based on the debug info that is present in bc files. If there is nothing there, then no debug info gets generated.
