### ISSUE TITLE
unsigned integer is not handled properly

### ISSUE THREAD

**Issue by muyaview** [smackers/smack#440]
unsigned integer is treated as signed. For below example:
```
int main(){
    unsigned short y = 60000;
    return y;
}
```
The corresponding bpl codes generated by llvm2bpl is (main function snippet):
```
const main: ref;
axiom (main == $sub.ref(0, 10341));
procedure {:entrypoint} main()
  returns ($r: i32)
{
  var $i0: i32;
$bb0:
  call $initialize();
  assume {:sourceloc "test.c", 3, 12} true;
  assume {:verifier.code 0} true;
  call {:cexpr "smack:entry:main"} boogie_si_record_ref(main);
  assume {:sourceloc "test.c", 3, 12} true;
  assume {:verifier.code 0} true;
  $i0 := $zext.i16.i32($sub.i16(0, 5536));
  call __SMACK_check_memory_leak();
  assume {:sourceloc "test.c", 3, 5} true;
  assume {:verifier.code 0} true;
  $r := $i0;
  $exn := false;
  return;
}
```
The value of $i0(variable y in c codes) is -5536 which is a signed number. 
This would bring unknown issues in verification process.

**Comment by shaobo-he** [comment]
SMACK does not precisely model integer arithmetic by default. In the example, `$sub.i16` is essentially subtraction for arbitrary precision integer. That's why you get `-5536`. If you want precise models, you may need to enable the `--bit-precise` flag. Then `$i0` will get value `$sub.bv16(0bv32, 5536bv32)` which evaluates to `60000bv16`.

**Comment by shaobo-he** [comment]
If there are further questions, plz reopen this isssue.
