### ISSUE TITLE
Remove symbooglix from back-end solvers

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#452]
It appears symbooglix is not maintained as opposed to Boogie/Corral and we never actively use it. I propose we remove it.

**Comment by zvonimir** [comment]
I actually would like to use it more since its algorithm (i.e., symbolic execution) is totally different from what Corral/Boogie are doing, and hence I expect it ought to have different properties in terms of scalability and performance. We just never found time to properly benchmark it, which we should do.
