### ISSUE TITLE
Inference of regions seems to be broken

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#473]
This is a small regression illustrating the issue:
```
#include "smack.h"
#include <stdlib.h>
int main(void)  {
  int* p = (int*)malloc(sizeof(int));
  *p = 1; 
  assert(*p != 2);  return 0;
}
```
The memory map that gets generated for these pointer accesses is of type `i8`, while they are clearly type safe and it should be of type `i32`. This seems to be due to the fact that we are generating regions even for instructions that do not access memory, such as `malloc`. More exploration is needed to get to the bottom of this.

**Comment by michael-emmi** [comment]
This is indeed what is happening. Specifically,  the `i8* @malloc` call gets an `i8` region, which overlaps with the following `bitcast`’s `i32` region, collapsing the type (effectively to `i8`). See here:
```
[regions] for:   %1 = call i8* @malloc(i64 4) #5, !dbg !31, !verifier.code !32
  in function: main
[regions]   using region: <Node:i8>[0,1]{A}
[regions]   returning index: 0

[regions] for:   %2 = bitcast i8* %1 to i32*, !dbg !33, !verifier.code !32
  in function: main
[regions]   using region: <Node:i32>[0,4]{A}
[regions]   found overlap at index 0: <Node:i8>[0,1]{A}
[regions]   merged region: <Node:*>[0,4]{A}
[regions]   returning index: 0
```
According to DSA’s principles, you’re also right that memory ought to be typed according to how it is accessed, not necessarily how it is allocated. Even so, I wonder whether we would still want malloc to impose an upper bound on the type, corresponding to its argument value. In this case we might give this call to malloc an `i32` region, and the resulting merged type would remain `i32`. In the case we’d allocated more space, e.g., 8 bytes, then perhaps we ought to consider the lower bound between `i32` and `i64` — currently we would fall straight down to `i8` since `i32` and `i64` are unequal. In the case we’d allocated less space, e.g., 2 bytes, then perhaps we’d want to create an `i16` region; this case would be type-unsafe.

What are your thoughts on that?

**Comment by zvonimir** [comment]
Sorry, but I don't exactly understand what you mean by "corresponding to its argument value". It seems you might be referring to the argument of malloc, but then I am not sure how we would always be able to know its value at compile time. It is also unclear to me what happens if a structure gets allocated, and not just a primitive type.

**Comment by michael-emmi** [comment]
Yes, “it’s argument” refers to “malloc’s argument”.

I meant this more as a discussion opener than a concrete suggestion, and agree with the unknowns you raise, e.g., that malloc’s argument value may not be known statically. If we think that malloc should influence region layouts, then we’d have to figure out how to deal with not knowing the argument statically, e.g., by falling back to region collapse in the worst case.

Anyhow, the discussion that I meant to raise is: should allocation (size) influence region layout?

**Comment by zvonimir** [comment]
I don't see why allocation (size) woud influence layout, but maybe I am missing something here.

The way I see it, regions are always of a primitive type/layout (I guess that is how you are using the term layout). They are either `i8` in the case of byte accesses or type unsafety, or they are of the respective type-safe type (`i32`, `i64`, etc.) based on how they are being accessed. I am not sure how allocation size could help a lot to infer these types. I think that what has to be done is to assign a region type/layout only when a memory location is actually being interpreted (load instruction, store instruction, maybe a few more). Another option (in terms of implementation) would be to leverage DSA types of memory locations to assign types/layouts to our regions. I hope this makes sense.

**Comment by michael-emmi** [comment]
But do you consider it to be type safe when malloc allocates only 1 byte, and subsequent accesses to the retuned pointer access 4 bytes?

Would you want to distinguish this case from the one where malloc actually allocated 4 bytes?

**Comment by zvonimir** [comment]
I see. I would say that the situation your described is type safe (type is `i32`) despite the fact that there is a buffer overflow.

**Comment by zvonimir** [comment]
In terms of regions, the two cases you listed should not be distinguished.

**Comment by michael-emmi** [comment]
Ah hah, that is interesting — it breaks my current understanding of what “type safety” is generally supposed to mean!

One part of my understanding is: the output of a type-safe program should not depend on system-level details, e.g., memory layout.

But this intuition is broken with the following program that seems type-safe in your interpretation:
```
int *x = (int*) malloc(1);
int *y = (int*) malloc(1);
*x = 0;
*y = -1;
assert( *x == 0 );
```
Here loads and stores are `int`-sized, but nevertheless this assertion can be violated if `y` is allocated, e.g., one byte from `x`.

So I guess my question is: which of these variations to “type safety” should we prefer?

**Comment by zvonimir** [comment]
Interesting example. Would alias analysis (like DSA) in this case report that `x` and `y` can alias (i.e., overlap)?
I think it would not. I would guess that alias analyses assume that there are no undefined behaviors, and that there are no soundness guarantees in the presence of undefined behaviors. So they can assume that there are no buffer overflows when performing the analysis. That's my hunch at least. Otherwise all bets are off anyways.

**Comment by zvonimir** [comment]
At the high-level, I don't know how one would go about defining type safety of programs with undefined behaviors, or even whether that would make sense.

**Comment by michael-emmi** [comment]
Hehe ok ok I think I'm starting to form an understanding now. But first I think we need to agree on terminology. From my understanding, the potential relationship you mention between “type safety” and “undefined behaviors” seems backwards. As you say, the type safety of undefined programs appears meaningless. But isn’t it that type-safe programs don’t have undefined behaviors — at least with respect to buffers/memory layout?

You are also right that DSA will not conclude that `x` and `y` many alias. And I think you’re right to think that alias analysis should assume type safety. Then I would conjecture the following consequence: assuming type safety, the size of allocations is completely irrelevant to the construction of memory regions, since: either (a) too-small an allocation would be type-unsafe, breaking the assumption, or (b) too-large an allocation cannot introduce any undesired behaviors (from the point of view of observed values). This all might already be well understood, but I’m not sure we’ve actually made this strong conclusion before.

So then I can agree with your initial suggestion that malloc should not be given a region when assuming type safety, and that this should prevent the undesirable situation raised by this issue.

However, I still wonder whether we should be careful about the other side: checking type safety. Currently, Smack (with the `--memory-safety` flag) will report an invalid pointer dereference on my example above. This is great, since it seems to provide an effective way to check the type-safety assumption. So I think we’d just want to be sure that the proposed fix (i.e., don’t give malloc a region) does not affect our ability to find type/memory safety violations.

**Comment by zvonimir** [comment]
Nice summary. Our memory model is unsound (or soundy), and there are definitely situations where we would not catch a memory safety violation (there are these "scoped" objects that I remember is one such unsound situation). I suspect there are others, and in particular in the presence of undefined behaviors.

Ok, but having said that, to me it seems that the proposed fix does not make our memory model less "soundy", if that makes sense.

**Comment by michael-emmi** [comment]
I’ve narrowed down the issue here:

https://github.com/smackers/smack/blob/c5f8613a70e1f1477b80bdc6576cbe2f03eafeba/lib/smack/SmackRep.cpp#L287-L290

Currently our criterion for determining whether a call is external includes that it does not return memory which DSA considers as program “allocated.” This check gets applied to malloc, and creates a region to access the underlying DSA node.

If we want to keep this criterion, then we should add an interface (e.g., to Regions) which allows checking whether DSA considers the node allocated, yet without actually creating a new region (and merging it with existing regions).

Here’s the call stack to the point where regions get merged for the call to `malloc`:
```
llvm2bpl!smack::Regions::idx(smack::Region&) (/Users/mje/Code/smack/lib/smack/Regions.cpp:270)
llvm2bpl!smack::Regions::idx(llvm::Value const*) (/Users/mje/Code/smack/lib/smack/Regions.cpp:246)
llvm2bpl!smack::SmackRep::isExternal(llvm::Value const*) (/Users/mje/Code/smack/lib/smack/SmackRep.cpp:289)
llvm2bpl!smack::SmackInstGenerator::visitCallInst(llvm::CallInst&) (/Users/mje/Code/smack/lib/smack/SmackInstGenerator.cpp:802)
llvm2bpl!llvm::InstVisitor<smack::SmackInstGenerator, void>::delegateCallInst(llvm::CallInst&) (/usr/local/Cellar/llvm@6/6.0.1_1/include/llvm/IR/InstVisitor.h:284)
llvm2bpl!llvm::InstVisitor<smack::SmackInstGenerator, void>::visitCall(llvm::CallInst&) (/usr/local/Cellar/llvm@6/6.0.1_1/include/llvm/IR/Instruction.def:190)
llvm2bpl!llvm::InstVisitor<smack::SmackInstGenerator, void>::visit(llvm::Instruction&) (/usr/local/Cellar/llvm@6/6.0.1_1/include/llvm/IR/Instruction.def:190)
llvm2bpl!void llvm::InstVisitor<smack::SmackInstGenerator, void>::visit<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, false> >(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, false>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, false>) (/usr/local/Cellar/llvm@6/6.0.1_1/include/llvm/IR/InstVisitor.h:92)
llvm2bpl!llvm::InstVisitor<smack::SmackInstGenerator, void>::visit(llvm::BasicBlock&) (/usr/local/Cellar/llvm@6/6.0.1_1/include/llvm/IR/InstVisitor.h:107)
llvm2bpl!void llvm::InstVisitor<smack::SmackInstGenerator, void>::visit<llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::BasicBlock, false, false, void>, false, false> >(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::BasicBlock, false, false, void>, false, false>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::BasicBlock, false, false, void>, false, false>) (/usr/local/Cellar/llvm@6/6.0.1_1/include/llvm/IR/InstVisitor.h:92)
llvm2bpl!llvm::InstVisitor<smack::SmackInstGenerator, void>::visit(llvm::Function&) (/usr/local/Cellar/llvm@6/6.0.1_1/include/llvm/IR/InstVisitor.h:103)
llvm2bpl!smack::SmackModuleGenerator::generateProgram(llvm::Module&) (/Users/mje/Code/smack/lib/smack/SmackModuleGenerator.cpp:77)
llvm2bpl!smack::SmackModuleGenerator::runOnModule(llvm::Module&) (/Users/mje/Code/smack/lib/smack/SmackModuleGenerator.cpp:31)
llvm2bpl!llvm::legacy::PassManagerImpl::run(llvm::Module&) (Unknown Source:0)
llvm2bpl!main (/Users/mje/Code/smack/tools/llvm2bpl/llvm2bpl.cpp:235)
libdyld.dylib!start (Unknown Source:0)
```

**Comment by zvonimir** [comment]
This is probably a dumb question and I am missing something here. But isn't being external equivalent to "returned from function that has external linkage"? Could we not use the `hasExternalLinkage` LLVM function?

**Comment by michael-emmi** [comment]
What we mean by external memory is that which is not allocated and used by the program, but by some library which we are not analyzing.

That is not exactly the same as external linkage because the program allocated and uses some memory returned from external-linkage functions like malloc.

**Comment by zvonimir** [comment]
You wrote "which is not allocated and used by the program". I understand the "not allocated" part, but I do not understand the "not used by the program" bit. As far as I know we do allow for external memory to be used by the program we are verifying, no?

I view malloc as currently being somewhat of a special case. If you look at: https://github.com/smackers/smack/blob/master/share/smack/lib/stdlib.c
you can see that we do provide bodies for memory allocation functions other than malloc, which means that they are not external linkage. Recently I wanted to provide a body for malloc as well in stdlib.c, but I failed. I forgot exactly why, I think I run into issues with `SMACK_code` and DSA.

What functions other than `malloc` (and other allocators such as `calloc`) have this behavior (external linkage but allocate memory)?
If such functions exist, to me it seems we should provide stubs/models for them anyways, and then they would not have external linkage any more.

**Comment by michael-emmi** [comment]
Short answers: (1) yes, we do allow for externally-allocated memory to be used, but that memory is separated from program-allocated memory, e.g., with `malloc`;

and (2) indeed making memory-allocation functions *internal* would simplify this logic, since we’d treat memory as externally-allocated iff it is returned by external functions. (The alternative solution I mentioned would be to keep the same logic, but allow access to DSA’s allocation information without necessarily creating regions.)

(Note: our characterization externally-allocated memory as that returned by external functions is not actually sound, since external functions may return program-allocated memory that has escaped into the arguments of external functions. So far we have accepted this unsoundness.)

**Comment by zvonimir** [comment]
I am fine with either solutions you mentioned under (2). To me it seems that relying on `hasExternalLinkage` plus a special case for `malloc` would be easier to implement (and probably cleaner), but I am fine with the other solution as well.

Related to your note, yes, there is this unsoundness issue for sure. One option would be to have a command line flag which, when selected, would cause for SMACK to assume that pointers returned from external functions can alias anything. That would be sound.

**Comment by zvonimir** [comment]
@michael-emmi Coming back to this issue, do you maybe have time this week to try to address it?
I can also work on the implementation if we agree on what the best fix would be.

**Comment by michael-emmi** [comment]
I don’t think I will have time this week, but I might be able to devote some mental cycles during the weekend. I’m also happy to just provide feedback, advice, and reviews, if you’d like to take a crack at it.

**Comment by zvonimir** [comment]
There is an interesting interplay between this issue and this regression: https://github.com/smackers/smack/blob/master/test/basic/extern_mem_fail.c

The fix I committed largely resolves the issue, but note that in the rare case where an external function returns i8 that later gets cast into something else, the collapsing of regions will still happen. I expect such cases to be quite rare though.
