### ISSUE TITLE
Confusing generated counterexample

### ISSUE THREAD

**Issue by JiaxiangLIU** [smackers/smack#483]
Dear developers,

I tried to use Smack 1.9.3 (the version downloaded at SV-COMP'19 website) to verify a cryptographic algorithm (in foo.c). It is as following:
<pre><code>#include "smack.h"
typedef unsigned long long u64;  // 64-bit unsigned integer
#define B ((u64)1 << 32)

int main(void) {
  u64 N = __VERIFIER_nondet_ulong();
  u64 Np = __VERIFIER_nondet_ulong();
  u64 T = __VERIFIER_nondet_ulong();

  if (  // pre-condition
      N < ((u64)1 << 31) && Np < B &&
      T < B * N && N % 2 == 1 &&
      (N * Np) % B == B - 1
     ) {

    const u64 btm32bits = 0xFFFFFFFF;
    u64 m = ((T & btm32bits) * Np) & btm32bits;
    u64 t = (T + m * N) >> 32;    

    // post-condition
    assert( (t * B) % N == T % N );
  }
  
  return 0;
}</code></pre>
The point is that the program contains bitwise instructions. And the program has been proven correct by hand.

I firstly used the `--bit-precise` option and respectively `boogie`, `corral` and `symbooglix` as back-ends to perform the verification. However, it seems too complicated for them to finish within 15 minutes. 

Then I tried without `--bit-precise`. `corral` returns a counterexample (in witness-corral.graphml) which confuses me. I list some useful information of the trace below:
<pre><code>    foo.c(9,11): Trace: Thread=1  (N = 3)
    foo.c(10,12): Trace: Thread=1  (Np = 1431655765)
    foo.c(11,11): Trace: Thread=1  (T = 0)
    foo.c(25,36): Trace: Thread=1  (m = 0)
    foo.c(26,25): Trace: Thread=1  (t = -1)
</code></pre>
According to the code, `m=0` makes sense because `T=0`. But my question is: why would `t=-1`? How does Smack calculate when producing the counterexample (trace)?

The second question: can I have any means to produce concrete counterexamples (I mean, with concrete values of the variables) using Boogie and Symbooglix? I does not find a way to do that like Corral.

Many thanks in advance!

PS: I produce the counterexample using Corral with the following command:
`smack --verifier corral -w witness-corral.graphml foo.c`
PPS: the C code and the witness file is included in [foo.zip](https://github.com/smackers/smack/files/3534271/foo.zip)

Best,
Jiaxiang

**Comment by michael-emmi** [comment]
To answer your first question: Smack calculates (via Corral) counterexample traces from the satisfying assignments of SMT formulas — those formulas characterize paths to assertion violations. You are seeing this anomaly because Smack has not ruled out the possibility that `t` could be negative. The following captures this even more concisely:
```bash
$ cat a.c && smack a.c | grep "y = "
```
```c
#include <smack.h>

unsigned int f();

int main(void) {
    unsigned int y = f();
    assert(y >= 0);
}
```
```
SMACK found an error.
    a.c(6,19):	Thread=1  y = -1
```
This might be resolved in a future release, but for now, you can manually enforce such constraints:
```c
#include <smack.h>

unsigned int f();

int main(void) {
    unsigned int y = f();
    assume(y >= 0);
    // ...
}
```

**Comment by michael-emmi** [comment]
To answer your second question (for Boogie, not sure about Simbooglix): Boogie could produce concrete values in principle, since it can access the satisfying assignments of the underlying SMT solver. Currently, however, this feature is not implemented in Boogie. I’m sure that a pull request (to Boogie) implementing that feature would be welcomed by many, in case you’re interested in undertaking that :-)

**Comment by JiaxiangLIU** [comment]
Dear @michael-emmi , thanks!
For my first question, I think you mean the reason is that Smack encodes both `int` and `unsigned int` as mathematical integers. But my confusion is more from the fact that I thought the value of `t` in the counterexample trace should depend on the values of `T`, `m` and `N`. Since `t = (T + m * N) >> 32` in the code, I thought this relation will remain in the SMT formula. Then in the returned trace, `t` should equal `(T + m * N) >> 32 = (0 + 0) >> 32 = 0`. But it seems I was wrong. What did I miss here?
For the second, yes you're right. Returning the concrete assignments of the satisfying SMT formulas is an important feature to check whether it is a real counterexample or not...

**Comment by michael-emmi** [comment]
Ah, well the independence of `t` from `T`, `m`, and `N` that you’re seeing is due to the fact that bitwise operations are not precisely modeled in bit-imprecise mode. Consider the following (and notice the warning emitted in bit-imprecise mode):
```
$ cat a.c && smack a.c --bit-precise && echo && smack a.c
```
```c
#include <smack.h>

int f() {
    return 1;
}

int main(void) {
     int x = f() << 2;
     assert(x == 4);
}
```
```
SMACK program verifier version 2.4.0
SMACK found no errors with unroll bound 1.
```
```
SMACK program verifier version 2.4.0
llvm2bpl: a.c:8:14: warning: over-approximating bitwise operation shl; try adding flag(s): --bit-precise 
/usr/local/share/smack/lib/smack.c(45,1): This assertion can fail
Execution trace:
    /usr/local/share/smack/lib/smack.c(521,3):	Thread=1  errno_global = 0
    /usr/local/share/smack/lib/smack.c(521,3):	Thread=1  
    /usr/local/share/smack/lib/smack.c(526,1):	Thread=1  
    a.c(8,10):	Thread=1  
    a.c(8,10):	Thread=1  
    a.c(8,10):	Thread=1  smack:entry:main = -7227
    a.c(8,10):	Thread=1  
    a.c(8,10):	Thread=1  CALL f
    a.c(4,2):	Thread=1  
    a.c(8,10):	Thread=1  RETURN from f
    a.c(8,14):	Thread=1  
    a.c(8,14):	Thread=1  x = 5
    a.c(9,2):	Thread=1  
    a.c(9,2):	Thread=1  CALL __VERIFIER_assert
    /usr/local/share/smack/lib/smack.c(258,29):	Thread=1  
    /usr/local/share/smack/lib/smack.c(258,29):	Thread=1  __VERIFIER_assert:arg:x = 0
    /usr/local/share/smack/lib/smack.c(258,29):	Thread=1  
    /usr/local/share/smack/lib/smack.c(45,3):	Thread=1  
    /usr/local/share/smack/lib/smack.c(45,3):	Thread=1  
    a.c(9,2):	Thread=1  RETURN from __VERIFIER_assert
    a.c(9,2):	Thread=1  

SMACK found an error.
```
What’s happening is that the left-shift operator `<<` gets interpreted as returning an arbitrary value, since there’s no straightforward interpretation of `<<` over mathematical integers.

It’s not clear how this might be resolved in future releases, but you could also manually add constraints on such operations like this:
```
$ cat a.c && smack a.c 
```
```c
#include <smack.h>

int f() {
	return 1;
}

int main(void) {
	int x = f() << 2;
	__SMACK_top_decl("axiom $shl.i32(1,2) == 4;");
	assert(x == 4);
	return 0;
}

SMACK program verifier version 2.4.0
llvm2bpl: a.c:8:14: warning: over-approximating bitwise operation shl; try adding flag(s): --bit-precise 
SMACK found no errors with unroll bound 1.
```
The invocation to `__SMACK_top_decl` basically adds a top-level Boogie declaration to the generated Boogie file; you can figure out which kinds of declarations to add by consulting the generated `.bpl` file:
```
$ smack -t a.c && head a.bpl 
SMACK program verifier version 2.4.0
llvm2bpl: a.c:8:14: warning: over-approximating bitwise operation shl; try adding flag(s): --bit-precise 
SMACK generated a.bpl
// generated by SMACK version 2.4.0 for corral
// via /usr/local/bin/smack -t a.c

// Basic types
type i1 = int;
type i5 = int;
type i6 = int;
type i8 = int;
type i16 = int;
type i24 = int;
```

**Comment by JiaxiangLIU** [comment]
Hi @michael-emmi , thank you very much for your detailed and clear answers! Now I understand better.
As for the second question, you mentioned that Boogie can access the satisfying assignments of the underlying SMT solver. Is there a way/option to let Boogie return these assignments? Or at least, is there a way/option to let Boogie return the satisfying SMT formulas? Otherwise, how could I check whether the reported counterexample is true or not?

**Comment by shaobo-he** [comment]
@JiaxiangLIU I closed this issue because it seems to me your questions have been answered. Feel free to re-open this issue if you have further questions.
