### ISSUE TITLE
Time out with "potential bug" (Corral as backend)

### ISSUE THREAD

**Issue by JiaxiangLIU** [smackers/smack#484]
Dear developers,

When I use Corral as the backend to verify my program, I got a timeout with the note "Program has a potential bug":
<pre><code>$ smack -v --verifier corral --time-limit 60 foo.c</code></pre>
<pre><code>SMACK program verifier version 1.9.3
Single threaded program detected
LB: Took 0.00 s
Verifying program while tracking: {assertsPassed}
Program has a potential bug: 
SMACK timed out.
</code></pre>

However, when I added the `--bit-precise` option, the note "Program has a potential bug" disappeared:
<pre><code>$ smack -v --bit-precise --verifier corral --time-limit 60 foo.c</code></pre>
<pre><code>SMACK program verifier version 1.9.3
Single threaded program detected
LB: Took 0.00 s
Verifying program while tracking: {assertsPassed}
SMACK timed out.
</code></pre>

What is the difference between these two kinds of timeouts? The first one did not return the "potential bug" it mentioned. 

Thanks in advance.

**Comment by JiaxiangLIU** [comment]
Here is what `foo.c` contains:
`$ cat foo.c`
<pre><code>#include "smack.h"
typedef unsigned long long u64;  // 64-bit unsigned integer
#define B ((u64)1 << 32)

int main(void) {
  u64 N = __VERIFIER_nondet_ulong();  assume(N >= 0);
  u64 Np = __VERIFIER_nondet_ulong();  assume(Np >= 0);
  u64 T = __VERIFIER_nondet_ulong();  assume(T >= 0);

  if (  // pre-condition
      0 < N && N < ((u64)1 << 31) &&
      0 < Np && Np < B && T < B * N &&
      N % 2 == 1 && (N * Np) % B == B - 1
     ) {

    const u64 btm32bits = 0xFFFFFFFF;
    u64 m = ((T & btm32bits) * Np) & btm32bits;  assume(m >= 0);
    u64 t = (T + m * N) >> 32;  assume(t >= 0);

    // post-condition
    assert( (t * B) % N == T % N );
  }
  return 0;
}</code></pre>
The two outputs with and without `--bit-precise` remain different (having "potential bug" or not) even if a larger time limit (e.g. 15min, 20min) is given. That means Corral is able to know that some SMT formula is satisfiable very quickly within 1min, but its computation of the satisfying assignments (to produce a trace) is too time-consuming (more than 20min). But I thought the satisfiability should be known only after the satisfying assignments are known.

**Comment by shaobo-he** [comment]
Based on my limited knowledge, Corral does abstraction refinement which means that when it reports the program having a potential bug, it doesn't really mean there's a true bug as Corral may be working on some abstraction of the real program. In the first example, Corral was performing the refinement when SMACK killed it due to time out whereas it didn't even get to the stage where it finds an error trace for the abstraction, so it didn't print program having a potential bug. You can get a better idea using Corral's toolflow below,

![image](https://user-images.githubusercontent.com/5892703/73787548-c4a40880-4758-11ea-9b67-4b3ef46e1585.png)

Please let me know if it makes sense or not.

**Comment by zvonimir** [comment]
This seems resolved to me, and so I am closing it.
