### ISSUE TITLE
How to handle regressions for multiple languages?

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#490]
So I would like to discuss design decisions related to adding Rust regressions to SMACK.

There are 3 ways we could do this (as far as I can see):
1. Add them into the `test` folder alongside C regressions. Maybe in this case we should refactor regressions into separate C and Rust folders.
2. We could introduce them as a git submodule.
3. They could reside in a separate repo. This is the case right now.

@keram88, @shaobo-he, @michael-emmi : what are your thoughts on this?

Now, I remember having this discussion with some of you, but I forgot what the conclusions were.

I think I am a proponent of option 1 above.

**Comment by zvonimir** [comment]
Oh, also should we run Rust regressions as a part of our CI?
I think we should if we are serious about Rust support.

**Comment by shaobo-he** [comment]
> So I would like to discuss design decisions related to adding Rust regressions to SMACK.
> 
> There are 3 ways we could do this (as far as I can see):
> 
> 1. Add them into the `test` folder alongside C regressions. Maybe in this case we should refactor regressions into separate C and Rust folders.
> 2. We could introduce them as a git submodule.
> 3. They could reside in a separate repo. This is the case right now.
> 
> @keram88, @shaobo-he, @michael-emmi : what are your thoughts on this?
> 
> Now, I remember having this discussion with some of you, but I forgot what the conclusions were.
> 
> I think I am a proponent of option 1 above.

I'm in favor of option 2. Btw, doesn't option 2 implies 3? The reason is that I want to make the SMACK repo only contain source code rather than tests. Imagine that the users only want to apply SMACK to C programs. Then, they need to download unnecessary Rust tests. I doubt they would care but making it optional may be appreciated. So, how about adding a flag to the build script like `--rust`? If it's enabled, we install Rust, clone Rust regressions, and run them.

**Comment by zvonimir** [comment]
No, 2 does not imply 3. They could be in a separate repo without being linked as a submodule, which is now the case.

Let me play a devils advocate here a little bit.

Yes, there are pros for linking regressions as a submodule. But note that there is an added maintenance cost for us that comes with submodules. For example, issues would have to somehow be split between repos. The same goes with fixes that require changing both source code and regressions. And so on.

If we had 10,000 regressions, I would definitely say we should put them into a separate repo. But for a few hundred I am not so sure since it is not a big overhead to pull them with everything else.

**Comment by michael-emmi** [comment]
I am in favor of some variation of Option 1: being in the same repository.

The reason is simple: these Rust-language tests are tests on the functionality of Smack itself, just like the C-code tests, and are meant to ensure that required functionality is not broken (regressed) by future commits.

Of course, actually running these tests can be contingent on the availability of a Rust compiler.

I’m not sure what the best way to organize these tests vs. C-code tests would be. Separating C code from Rust code as @zvonimir proposes seems like a reasonable option.
