### ISSUE TITLE
Global variables not cleaned up after being optimized

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#59]
When memory accesses to a global variable are optimized into scalar accesses, the global variable in question is not removed. Hence we often end up with many unused global variables in bpl files, which would be nice to clean up a bit.

**Comment by Guoanshisb** [comment]
I'm comparing the performance of SMACK with that of LLBMC since they are both based on LLVM IR code. At first it was frustrating that LLBMC (less than 1s) is way faster than SMACK with bitvector (20s). What surprised me is that if the unnecessary globals (like `const unique .str*`) were removed from `.bpl` files. The verification time (`corral testfile.bpl`) is reduced significantly (20s to less 1s). So I guess we should try to get rid of them.

**Comment by michael-emmi** [comment]
In general, globals cannot be removed just because their accesses are compiled to scalar accesses. Their address, for instance, can still be taken. Consider adding the following line to the `globals.c` regression:
````
assert(&g1 == &g2 + 1);
````
Arguably, one should probably not make assertions about memory layout. But the point is that the addresses of globals can still be used, and thus their declarations must be kept.
