### ISSUE TITLE
Upgrading SMACK to LLVM 11

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#691]
Hey guys,

I just did a quick experiment to upgrade SMACK to LLVM 11. It seems the most challenging part is to handle LLVM's change where implicit cast from `llvm::StringRef` to `std::string` is removed. This motivates us to think about the question of whether we should just use `llvm::StringRef`.

**Comment by zvonimir** [comment]
Could you give me an example? They removed such cast?

**Comment by shaobo-he** [comment]
> Could you give me an example? They removed such cast?

https://github.com/smackers/smack/blob/ae85a253ccde7da04f3c37ddc9c76425ed0b3e85/lib/smack/IntegerOverflowChecker.cpp#L124

Clang reports a compilation error for the line above because `getName` returns `StringRef` while `isSmackName` accepts `std::string`.

**Comment by zvonimir** [comment]
Ok, got it. I think there are two solutions here:
(1) Every time we expect a `std::string` and LLVM gives us `StringRef`, we create a string from it. So there is a level of indirection here.
(2) Instead of using `std::string` we switch to using `StringRef` in our code.

To me it seems that (2) is probably a slightly better solution.
