### ISSUE TITLE
Question regarding D support

### ISSUE THREAD

**Issue by roxanaRA** [smackers/smack#709]
Hello,

I am working on a project to verify D contracts and I want to use SMACK. I saw that SMACK has support for D.

Are there some new/missing functionalities which could be added in SMACK in order to extend the support for D?

**Comment by zvonimir** [comment]
Thanks for your interest in SMACK! Our support for D is most definitely prototypical, but D seems to be the kind of language that is well without our reach.
It would be super useful for us if you could send a few (smallish) benchmarks our way, since that would drive our development. We are definitely interested in helping out to make D support more mature.

**Comment by roxanaRA** [comment]
Thank you for your response.

Can you give me some details/examples of the benchmarks you mentioned?

**Comment by keram88** [comment]
Hello,
Some examples of small benchmarks (and supported/unsupported features) can be found here: https://github.com/soarlab/gandalv/tree/master/d
New benchmarks would come from programs which unexpectedly fail, which have been reduced to some unsupported feature of the language.

**Comment by zvonimir** [comment]
To clarify this further, if you could send our way examples of D programs that you would like to verify, that would be great!

**Comment by roxanaRA** [comment]
Thank you for your answer.
