### ISSUE TITLE
smack gives erratic result when data can overflow

### ISSUE THREAD

**Issue by fugyk** [smackers/smack#73]
This program is successfully verified by smack while it's wrong.
```
#include "smack.h"
int main() {
  int x = __SMACK_nondet();
  assert(x < x+2147483647);
  return 0;
}
```
This is certainly not true for all positive x.

And as a surprising behaviour as smack outputs assertion might not be true in the following code.
 ```
#include "smack.h"
int main() {
  int x = __SMACK_nondet();
  assert(x < x+599147937792);
  return 0;
}
```
All values less than 599147937792 can be verified.

**Comment by michael-emmi** [comment]
Actually, the first program is correct when you assume that integers have unbounded width, i.e., they are not bounded by 32 bits. This is how SMACK models integers by default. If you want to model integers with architecture-dependent bounded widths instead, simply invoke SMACK with the flag `--bit-precise`.

SMACK’s behavior on the second program is indeed strange. We’ll take a look soon.

**Comment by michael-emmi** [comment]
A fix to develop has been pushed. Note that even with bit precision turned on, the assertion cannot fail in the second program. The reason is that `x` is declared as an `int`, and thus can hold a 32-bit value, while the addition happens in 64-bit arithmetic. The 64-bit addition of `599147937792` with any 32-bit value cannot overflow. You’ll need bigger numbers to violate that assertion :-).
