### ISSUE TITLE
Pointer Tests Fail and Timeout

### ISSUE THREAD

**Issue by jon-whit** [smackers/smack#77]
I'm running off of the `develop` branch on Ubuntu. Two of the pointer tests are failing and four of them are timing out:

```
==> ubuntu:   ./bits/pointers5.c
==> ubuntu:                reuse     boogie    : TIMEOUT   [10.68s]
==> ubuntu:                reuse     corral    : TIMEOUT   [10.90s]
==> ubuntu:   ./bits/pointers6.c
==> ubuntu:                reuse     boogie    : FAILED    [1.08s]
==> ubuntu:                reuse     corral    : FAILED    [1.93s]
==> ubuntu:   ./bits/pointers7.c
==> ubuntu:                reuse     boogie    : TIMEOUT   [10.71s]
==> ubuntu:                reuse     corral    : TIMEOUT   [10.89s]
```

I don't see any active Issues regarding these tests. Does anyone else fail these?

**Comment by michael-emmi** [comment]
Hey Jonathan, thanks for raising this issue. We are aware, and are considering fixes, but it’s good to have the issue open too.

**Comment by jon-whit** [comment]
@michael-emmi 

Your welcome. I just wanted to make sure I wasn't getting abnormal test results during the build.

**Comment by zvonimir** [comment]
I was actually thinking about this as we are preparing for a new release.
It would be good that our default run of regtest.py has no failing regressions. Since we will almost certainly be getting emails asking about why some regressions are failing.
Then we could have an option called "complete" or something like that, which would run all regressions, including the failing ones. That one would be primarily used by us and experts...

**Comment by michael-emmi** [comment]
The issue with `bits/pointers6.c` is fixed, though the other two are still timing out.

**Comment by zvonimir** [comment]
Quick comment for future reference: We ultimately fixed this by moving failing regressions into a separate dedicated folder.
